force-app/main/default/objects/Incident_IOT__c/Incident_IOT__c.object-meta.xml
<CustomObject>
    <label>Incident_IOT</label>
    <nameField>
        <label>Incident_IOT_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents_IOT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident_IOT__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>IOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident_IOT__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident_IOT__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IoTChartControllerTest.cls
@isTest
private class IoTChartControllerTest {
    @isTest
    static void getIotData() {
        // Create test data
        List<Incident_IOT__c> testIoTData = new List<Incident_IOT__c>();
        for(Integer i=0; i<10; i++) {
            Incident_IOT__c opp = new Incident_IOT__c(Name='Test IoT Data '+i, Origin__c='System', Status__c='New', Subject__c='Test IoT Data');
            testIoTData.add(opp);
        }
        insert testIoTData;
        // Call the method to be tested
        Test.startTest();
        List<Incident_IOT__c> result = IoTChartController.getIotData();
        Test.stopTest();
        // Verify the result
        System.assertEquals(10, result.size(), 'Expected 10 IoT Data');
        for(Integer i=0; i<10; i++) {
            Incident_IOT__c expectedOpp = testIoTData[i];
            Incident_IOT__c actualOpp = result[i];
            System.assertEquals(expectedOpp.Name, actualOpp.Name, 'Name should match');
            System.assertEquals(expectedOpp.Origin__c, actualOpp.Origin__c, 'Origin should match');
        }
    }
}